#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config mouse_follows_focus           on
yabai -m config focus_follows_mouse           autoraise
yabai -m config window_opacity                on
yabai -m config window_shadow                 on
yabai -m config insert_feedback_color         0xffd75f5f
yabai -m config split_ratio                   0.50
yabai -m config auto_balance                  on

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_opacity_duration 0.0

yabai -m config layout float

yabai -m config --space 1 layout float
yabai -m config --space 2 layout stack
yabai -m config --space 3 layout float
yabai -m config --space 4 layout bsp
yabai -m config --space 5 layout bsp
yabai -m config --space 6 layout stack
yabai -m config --space 7 layout float

yabai -m config window_placement second_child

yabai -m config top_padding 12
yabai -m config bottom_padding 38
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

yabai -m rule --add app="^Thunderbird$" space=3
yabai -m rule --add app="^Kitty$" space=2
yabai -m rule --add app="^Firefox$" space=^5

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Finder$" manage=off
